server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8089/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: eureka-service